### ISSUE TITLE
Building fails with error because of using auto function while compiling with -std=gnu++11

### ISSUE THREAD

**Issue by h8ghbzc9bbr8c7** [ONLYOFFICE/build_tools#308]
**Description**

Builiding fails on Ubuntu 18.04 because of using a auto function while compiling with -std=gnu++11 which results in the following error:

```
src/cascapplicationmanagerwrapper_private.h:104:21: error: ‘mainWindow’ function uses ‘auto’ type specifier without trailing return type
     auto mainWindow() {
                     ^
src/cascapplicationmanagerwrapper_private.h:104:21: note: deduced return type only available with -std=c++14 or -std=gnu++14

```
**Steps to reproduce the problem**:

Call ./automate.py

**build_tools base repo version**:

bd3568e

**Operating system**:

Ubuntu 18.04

**Compiler version**:

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by h8ghbzc9bbr8c7** [comment]
The change was introduced with commit e2b0dd9ee15b7155339ede186f6e8f622bc684bd in desktop-apps.

**Comment by ShockwaveNN** [comment]
This problem is already resolved in v6.3.0 via [this](https://github.com/ONLYOFFICE/desktop-apps/commit/b2b3d013d610cb8e745b98cd9022bd0538e34a9e#diff-9e20bf2b913a327abb5a3cac50c90fa38ed1fd966260608271b64d56f2c27199R115)

We hope to release v6.3.0 soon, in week or two

**Comment by ShockwaveNN** [comment]
We release v6.3.0 for quite some time and this problem should be fixed
